"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import os

from pathlib import Path
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# Security headers emitted by Django's SecurityMiddleware
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_countries",
    "wallet",
    "drf_spectacular",
    "oauth2_provider",
    "allauth",
    "allauth.account",
    "auth_kit",
    "auth_kit.mfa",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "auth_kit.social",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "auth_kit.authentication.JWTCookieAuthentication",
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/minute",
        "user": "300/minute",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=30),
}

ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
# Auto-connect is intentionally disabled: connecting a social account to an
# existing password account based solely on email match is an account-takeover
# vector if the social provider does not enforce email verification at the app
# layer (FETCH_USERINFO is False, so email_verified is not independently checked).
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = False
# "optional" still lets Google users sign up, but an unverified social email
# will not silently inherit an existing verified account.
SOCIALACCOUNT_EMAIL_VERIFICATION = "optional"


AUTH_USER_MODEL = "wallet.CustomUser"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

OAUTH2_PROVIDER_APPLICATION_MODEL = "oauth2_provider.Application"

OAUTH2_PROVIDER = {
    "OAUTH2_VALIDATOR_CLASS": "wallet.oauth_validators.CustomOAuth2Validator",
    "OIDC_ENABLED": True,
    "OIDC_RSA_PRIVATE_KEY": os.getenv("OIDC_RSA_PRIVATE_KEY"),
    "SCOPES_BACKEND_CLASS": "wallet.scopes_backend.DynamicScopesBackend",
}

LOGIN_URL = "/accounts/login/"

AUTH_KIT = {
    "AUTH_TYPE": "jwt",
    "USE_AUTH_COOKIE": True,
    "USE_MFA": True,
    "SOCIAL_LOGIN_AUTH_TYPE": "code",
    "SOCIAL_LOGIN_CALLBACK_BASE_URL": "http://localhost:5173/auth/callback",
    "SOCIAL_LOGIN_SERIALIZER_FACTORY": "wallet.social_serializers.get_pkce_social_login_serializer",
    "SOCIAL_CONNECT_CALLBACK_BASE_URL": "http://localhost:5173/auth/callback",
    "SOCIAL_CONNECT_VIEW": "wallet.social_serializers.PKCESocialConnectView",
    # Default True: social account email must match the authenticated user's email.
    # "SOCIAL_CONNECT_REQUIRE_EMAIL_MATCH": True,
    # Frontend URL configuration for email links
    "FRONTEND_BASE_URL": "http://localhost:5173",
    "REGISTER_EMAIL_CONFIRM_PATH": "/auth/verify-email",
    "PASSWORD_RESET_CONFIRM_PATH": "/auth/reset-password",  # nosec B105
    # TOTP Configuration
    "MFA_TOTP_DEFAULT_INTERVAL": 30,  # Code validity (seconds)
    "MFA_TOTP_DEFAULT_VALID_WINDOW": 1,  # Clock skew tolerance (±1 window = 3 codes checked)
    # Backup Codes
    "NUM_OF_BACKUP_CODES": 5,  # Number of backup codes
    "BACKUP_CODE_LENGTH": 12,  # Backup code length
    "BACKUP_CODE_SECURE_HASH": True,  # Secure storage
    # Token Expiry
    "MFA_EPHEMERAL_TOKEN_EXPIRY": 900,  # 15 minutes  # nosec B105
    # App Settings
    "MFA_APPLICATION_NAME": "TrustVault",  # Shown in authenticator apps
    # Security Constraints
    "MFA_PREVENT_DELETE_ACTIVE_METHOD": False,
    "MFA_PREVENT_DELETE_PRIMARY_METHOD": True,
    "MFA_DELETE_ACTIVE_METHOD_REQUIRE_CODE": True,

}

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
        "FETCH_USERINFO": False,
        "APP": {
            "client_id": GOOGLE_CLIENT_ID,
            "secret": GOOGLE_CLIENT_SECRET,
            "key": "",
        },
    },
}

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
# EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
# EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
# EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
# DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

EMAIL_HOST = "0.0.0.0"  # nosec B104
EMAIL_PORT = 1025
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''  # nosec B105
EMAIL_USE_TLS = False


# CORS and Session Configuration
# Set CORS_ALLOWED_ORIGINS / CSRF_TRUSTED_ORIGINS as comma-separated URLs in
# the environment file. Defaults cover local dev only.
CORS_ALLOW_CREDENTIALS = True
_cors_default = "http://localhost:5173,http://127.0.0.1:5173,http://localhost:8001"
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv("CORS_ALLOWED_ORIGINS", _cors_default).split(",")
    if o.strip()
]
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("CSRF_TRUSTED_ORIGINS", _cors_default).split(",")
    if o.strip()
]
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"