# Generated by Django 6.0.5 on 2026-05-08 14:06

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Context Type',
                'verbose_name_plural': 'Context Types',
            },
        ),
        migrations.CreateModel(
            name='PrivacyMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(max_length=50)),
                ('disclosure', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Metadata',
                'verbose_name_plural': 'Privacy Metadata',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(max_length=150)),
                ('relying_party', models.CharField(max_length=255)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfBirth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birth_country', django_countries.fields.CountryField(max_length=2)),
                ('birth_state', models.CharField(max_length=255)),
                ('birth_city', models.CharField(max_length=255)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_of_birth', to='wallet.contexttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='place_of_birth', to=settings.AUTH_USER_MODEL)),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='place_of_birth', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Place of Birth',
            },
        ),
        migrations.CreateModel(
            name='OnlineProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_fields', models.JSONField(blank=True, null=True)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_profiles', to='wallet.contexttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_profiles', to=settings.AUTH_USER_MODEL)),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_profiles', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Online Profile',
                'verbose_name_plural': 'Online Profiles',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationality', to='wallet.contexttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationalities', to=settings.AUTH_USER_MODEL)),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nationality', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
            },
        ),
        migrations.CreateModel(
            name='NameHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('given_name', models.CharField(max_length=255)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_histories', to='wallet.contexttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_histories', to=settings.AUTH_USER_MODEL)),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name_histories', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Name History',
                'verbose_name_plural': 'Name Histories',
            },
        ),
        migrations.CreateModel(
            name='LegalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('given_name', models.CharField(max_length=255)),
                ('family_name_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('given_name_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_identity', to='wallet.contexttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_identity', to=settings.AUTH_USER_MODEL)),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_identity', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Legal Identity',
                'verbose_name_plural': 'Legal Identities',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=255)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='wallet.contexttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genders', to=settings.AUTH_USER_MODEL)),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='DailyUse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_uses', to='wallet.contexttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_uses', to=settings.AUTH_USER_MODEL)),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_uses', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Daily Use Identity',
                'verbose_name_plural': 'Daily Use Identities',
            },
        ),
        migrations.CreateModel(
            name='CustomObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_objects', to='wallet.contexttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_objects', to=settings.AUTH_USER_MODEL)),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_objects', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Custom Object',
                'verbose_name_plural': 'Custom Objects',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_name', models.CharField(max_length=255)),
                ('credential_type', models.CharField(max_length=255)),
                ('credential_description', models.TextField()),
                ('credential_id', models.CharField(max_length=255)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('issuance_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('credential_url', models.URLField(blank=True, max_length=500, null=True)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='wallet.contexttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='age', to=settings.AUTH_USER_MODEL)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ages', to='wallet.contexttype')),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ages', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Age',
                'verbose_name_plural': 'Ages',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(max_length=50)),
                ('resident_country', django_countries.fields.CountryField(max_length=2)),
                ('resident_state', models.CharField(max_length=255)),
                ('resident_city', models.CharField(max_length=255)),
                ('resident_postal_code', models.CharField(max_length=30)),
                ('resident_street', models.CharField(max_length=255)),
                ('resident_house_number', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='wallet.contexttype')),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='wallet.privacymetadata')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=255, null=True)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_identities', to='wallet.contexttype')),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_identities', to='wallet.privacymetadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional Identity',
                'verbose_name_plural': 'Professional Identities',
            },
        ),
        migrations.CreateModel(
            name='Pseudonym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relying_party', models.CharField(max_length=255)),
                ('pseudonym_value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pseudonyms', to='wallet.contexttype')),
                ('privacy_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pseudonyms', to='wallet.privacymetadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pseudonyms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pseudonym Identity',
                'verbose_name_plural': 'Pseudonym Identities',
            },
        ),
    ]
