# Generated by Django 6.0.5 on 2026-05-15 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0003_alter_placeofbirth_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privacymetadata",
            options={
                "verbose_name": "Privacy Metadata",
                "verbose_name_plural": "Privacy Metadata Records",
            },
        ),
        migrations.RenameField(
            model_name="customobject",
            old_name="attributes",
            new_name="attribute_value",
        ),
        migrations.AddField(
            model_name="customobject",
            name="attribute_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
