# Generated by Django 6.0.5 on 2026-05-15 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_privacymetadata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customobject',
            old_name='attribute_name',
            new_name='name_type',
        ),
        migrations.RemoveField(
            model_name='customobject',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='customobject',
            name='name_value',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
