# Generated by Django 6.0.5 on 2026-05-16 13:10

import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0005_rename_attribute_name_customobject_name_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customobject",
            name="name_type",
            field=models.CharField(
                max_length=255, validators=[wallet.models.validate_scope_name]
            ),
        ),
    ]
